In [ ]:
!pip install tvdatafeed
!pip install tensorflow
!pip install scikit-learn

ERROR: Could not find a version that satisfies the requirement tvdatafeed (from versions: none)
ERROR: No matching distribution found for tvdatafeed


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/My\ Drive/Colab\ Notebooks/

Mounted at /content/drive
 AItinyfoodrecog	   'Copy of GNN.ipynb'	        GNNs			'WiDs Investron'
 cGAN			   'Copy of Welcome To Colab'   ProjectAiFoodRecogn
'Copy of AItinyfoodrecog'   data		       ' ProjectAiFoodRecogn2'


In [ ]:
!ls /content/drive/My\ Drive/Colab\ Notebooks/
import os

directory = "/content/drive/My Drive/Colab Notebooks/data/"

if os.path.exists(directory):
    print("Directory exists!")
    print("Files in directory:", os.listdir(directory))
else:
    print("Directory does not exist. Check the path.")


 AItinyfoodrecog	   'Copy of GNN.ipynb'	        GNNs			'WiDs Investron'
 cGAN			   'Copy of Welcome To Colab'   ProjectAiFoodRecogn
'Copy of AItinyfoodrecog'   data		       ' ProjectAiFoodRecogn2'
Directory exists!
Files in directory: ['DRREDDY.csv', 'M&M.csv', 'INDUSINDBK.csv', 'EICHERMOT.csv', 'WIPRO.csv', 'BAJFINANCE.csv', 'TATAMOTORS.csv', 'BAJAJFINSV.csv', 'CIPLA.csv', 'SUNPHARMA.csv', 'TRENT.csv', 'TECHM.csv', 'ICICIBANK.csv', 'NESTLEIND.csv', 'INFY.csv', 'ITC.csv', 'ASIANPAINT.csv', 'MARUTI.csv', 'RELIANCE.csv', 'HDFCBANK.csv', 'HINDUNILVR.csv', 'KOTAKBANK.csv', 'ADANIENT.csv', 'NTPC.csv', 'AXISBANK.csv', 'BRITANNIA.csv', 'TCS.csv', 'BHARTIARTL.csv', 'GRASIM.csv', 'JSWSTEEL.csv', 'APOLLOHOSP.csv', 'POWERGRID.csv', 'TITAN.csv', 'SBILIFE.csv', 'ULTRACEMCO.csv', 'HCLTECH.csv', 'LT.csv', 'BPCL.csv', 'HDFCLIFE.csv', 'HEROMOTOCO.csv', 'TATASTEEL.csv', 'ADANIPORTS.csv', 'BEL.csv', 'SHRIRAMFIN.csv', 'ONGC.csv', 'SBIN.csv', 'COALINDIA.csv', 'MockBroker.py', 'HINDALCO.csv', 'Investron.py'

In [1]:
# Required Libraries
import os
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define Data Directory
data_dir = "/content/drive/My Drive/Colab Notebooks/data/"

# Load Data into Dictionary of DataFrames
def load_data(data_dir):
    dataframe_dict = {}
    for file in os.listdir(data_dir):
        if file.endswith(".csv"):  # Ensure only CSV files are considered
            symbol = file.split(".")[0]  # Extract symbol from filename
            dataframe_dict[symbol] = pd.read_csv(os.path.join(data_dir, file))
    return dataframe_dict

dataframe_dict = load_data(data_dir)

# Splitting Data into Train and Test Sets
train_days = 900
sequence_length = 30  # Number of days in each sequence

def split_data(df, train_days):
    train_data = df.iloc[:train_days]
    test_data = df.iloc[train_days:]
    return train_data, test_data

# Prepare Sequences for LSTM
def create_sequences(data, sequence_length, feature_columns, target_column):
    X, y = [], []
    for i in range(len(data) - sequence_length):
        X.append(data.iloc[i:i + sequence_length][feature_columns].values)
        y.append(data.iloc[i + sequence_length][target_column])
    return np.array(X), np.array(y)

# Normalize Data
scaler = MinMaxScaler()

# Define LSTM Model
def create_model(input_shape):
    model = Sequential([
        LSTM(64, input_shape=input_shape, return_sequences=True),
        Dropout(0.2),
        LSTM(64, return_sequences=False),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(1, activation='tanh')  # Output: -1 to 1
    ])
    model.compile(optimizer='adam', loss='mse')
    return model

# Train Models and Predict for Each Company
predictions = {}
test_data_dict = {}
for symbol, df in dataframe_dict.items():
    print(f"Processing {symbol}...")
    train_data, test_data = split_data(df, train_days)
    test_data_dict[symbol] = test_data.reset_index(drop=True)

    feature_columns = ['MACD', 'RSI', 'close']  # Features for LSTM
    target_column = 'positions'  # Target: -1, 0, 1 (sell, hold, buy)

    X_train, y_train = create_sequences(train_data, sequence_length, feature_columns, target_column)
    X_test, y_test = create_sequences(test_data, sequence_length, feature_columns, target_column)

    # Scale Data
    X_train = scaler.fit_transform(X_train.reshape(-1, X_train.shape[-1])).reshape(X_train.shape)
    X_test = scaler.transform(X_test.reshape(-1, X_test.shape[-1])).reshape(X_test.shape)

    # Train Model
    model = create_model((sequence_length, len(feature_columns)))
    model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=0)

    # Predict on Test Data
    y_pred = model.predict(X_test)
    y_pred = np.where(y_pred > 0, 1, np.where(y_pred < 0, -1, 0))  # Convert to discrete signals
    predictions[symbol] = y_pred
    # Convert predictions to actionable signals
    threshold_buy = 0.5  # You can adjust these thresholds
    threshold_sell = -0.5

    # Generate buy (1), sell (-1), hold (0) actions
    actions = np.where(y_pred > threshold_buy, 1, np.where(y_pred < threshold_sell, -1, 0))
    predictions[symbol] = actions  # Assign processed actions to predictions


# MockBroker Class
class MockBroker:
    def __init__(self, initial_balance: float, price_data: dict):
        """
        Initialize MockBroker with starting balance and price dictionary for multiple companies.

        Args:
            initial_balance: Starting cash balance
            price_data: Dictionary with stock symbols as keys and their respective DataFrame of prices as values
        """
        self.balance = initial_balance
        self.price_data = price_data
        self.holdings = {symbol: 0 for symbol in price_data.keys()}  # Initialize holdings for all companies
        self.current_day = 0

    def get_current_price(self, symbol: str) -> float:
        """Get the current price for a symbol based on current_day"""
        return self.price_data[symbol].iloc[self.current_day]['close']

    def buy(self, symbol: str, quantity: int) -> bool:
        """Buy specified quantity of a stock if sufficient balance exists"""
        cost = self.get_current_price(symbol) * quantity
        if cost > self.balance:
            return False
        self.balance -= cost
        self.holdings[symbol] += quantity
        return True

    def sell(self, symbol: str, quantity: int) -> bool:
        """Sell specified quantity of a stock if sufficient holdings exist"""
        if self.holdings[symbol] < quantity:
            return False
        proceeds = self.get_current_price(symbol) * quantity
        self.balance += proceeds
        self.holdings[symbol] -= quantity
        return True

    def get_net_worth(self) -> float:
        """Calculate total net worth (cash + value of holdings)"""
        holdings_value = sum(
            self.get_current_price(symbol) * quantity
            for symbol, quantity in self.holdings.items()
        )
        return self.balance + holdings_value

    def next_day(self):
        """Advance to the next trading day"""
        self.current_day += 1

# Simulate Trading for All Companies
broker = MockBroker(10000, test_data_dict)

for i in range(len(test_data_dict['HINDALCO'])):  # Assume all companies have same test days
    for symbol in predictions.keys():
        broker.current_day = i
        action = predictions[symbol][i] if i < len(predictions[symbol]) else 0
        print(f"Day {i}, Symbol: {symbol}, Action: {action}")
        if action == 1:  # Buy
            broker.buy(symbol, 10)
        elif action == -1:  # Sell
            broker.sell(symbol, 10)

# Final Results
print(f"Final Balance: ${broker.balance:.2f}")
print(f"Final Net Worth: ${broker.get_net_worth():.2f}")


Mounted at /content/drive
Processing DRREDDY...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing M&M...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
Processing INDUSINDBK...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/3 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Processing EICHERMOT...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing WIPRO...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 226ms/step
Processing BAJFINANCE...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
Processing TATAMOTORS...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
Processing BAJAJFINSV...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Processing CIPLA...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing SUNPHARMA...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
Processing TRENT...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing TECHM...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Processing ICICIBANK...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Processing NESTLEIND...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
Processing INFY...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing ITC...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing ASIANPAINT...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
Processing MARUTI...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Processing RELIANCE...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Processing HDFCBANK...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing HINDUNILVR...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
Processing KOTAKBANK...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing ADANIENT...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Processing NTPC...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Processing AXISBANK...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Processing BRITANNIA...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Processing TCS...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing BHARTIARTL...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
Processing GRASIM...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Processing JSWSTEEL...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing APOLLOHOSP...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
Processing POWERGRID...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Processing TITAN...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
Processing SBILIFE...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing ULTRACEMCO...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
Processing HCLTECH...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Processing LT...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing BPCL...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Processing HDFCLIFE...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
Processing HEROMOTOCO...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
Processing TATASTEEL...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Processing ADANIPORTS...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
Processing BEL...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Processing SHRIRAMFIN...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Processing ONGC...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
Processing SBIN...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
Processing COALINDIA...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
Processing HINDALCO...


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Day 0, Symbol: DRREDDY, Action: [0]
Day 0, Symbol: M&M, Action: [0]
Day 0, Symbol: INDUSINDBK, Action: [0]
Day 0, Symbol: EICHERMOT, Action: [0]
Day 0, Symbol: WIPRO, Action: [0]
Day 0, Symbol: BAJFINANCE, Action: [0]
Day 0, Symbol: TATAMOTORS, Action: [0]
Day 0, Symbol: BAJAJFINSV, Action: [0]
Day 0, Symbol: CIPLA, Action: [0]
Day 0, Symbol: SUNPHARMA, Action: [0]
Day 0, Symbol: TRENT, Action: [0]
Day 0, Symbol: TECHM, Action: [0]
Day 0, Symbol: ICICIBANK, Action: [0]
Day 0, Symbol: NESTLEIND, Action: [0]
Day 0, Symbol: INFY, Action: [0]
Day 0, Symbol: ITC, Action: [0]
Day 0, Symbol: ASIANPAINT, Action: [0]
Day 0, Symbol: MARUTI, Action: [0]
Day 0, Symbol: RELIANCE, Action: [0]
Day 0, Symbol: HDFCBANK, Action: [0]
Day 0, Symbol: HINDUNILVR, Action: [0]
Day 0, Symbol: KOTAKBANK, Action: [0]
Day 0, Symbol: ADANIENT, Action: [0]
Day 0, Symbol: NTPC, Action: [0]
Day 0, Symbol: AXISBANK, Action: [0]
Day 0, Symbol: BRITANNIA, Action: [0]
Day 0, Symbol: 

In [ ]:
# Required Libraries
import os
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from google.colab import drive
import tensorflow as tf

# Mount Google Drive
drive.mount('/content/drive')

# Define Data Directory
DATA_DIR = "/content/drive/My Drive/Colab Notebooks/data/"

class DataLoader:
    def __init__(self, data_dir):
        self.data_dir = data_dir
        self.scaler = MinMaxScaler()

    def load_data(self):
        dataframe_dict = {}
        for file in os.listdir(self.data_dir):
            if file.endswith(".csv"):
                symbol = file.split(".")[0]
                df = pd.read_csv(os.path.join(self.data_dir, file))
                print(df)
                # Ensure required columns exist
                required_columns = ['MACD', 'RSI', 'close', 'positions']
                if not all(col in df.columns for col in required_columns):
                    raise ValueError(f"Missing required columns in {file}")
                dataframe_dict[symbol] = df
        return dataframe_dict

    def prepare_data(self, df, train_days, sequence_length):
        # Split data
        train_data = df.iloc[:train_days]
        test_data = df.iloc[train_days:]

        feature_columns = ['MACD', 'RSI', 'close']
        target_column = 'positions'

        # Create sequences
        X_train, y_train = self._create_sequences(train_data, sequence_length, feature_columns, target_column)
        X_test, y_test = self._create_sequences(test_data, sequence_length, feature_columns, target_column)

        # Scale data
        X_train_scaled = self.scaler.fit_transform(X_train.reshape(-1, X_train.shape[-1])).reshape(X_train.shape)
        X_test_scaled = self.scaler.transform(X_test.reshape(-1, X_test.shape[-1])).reshape(X_test.shape)

        return X_train_scaled, y_train, X_test_scaled, y_test, test_data.reset_index(drop=True)

    def _create_sequences(self, data, sequence_length, feature_columns, target_column):
        X, y = [], []
        for i in range(len(data) - sequence_length):
            X.append(data.iloc[i:i + sequence_length][feature_columns].values)
            y.append(data.iloc[i + sequence_length][target_column])
        return np.array(X), np.array(y)

class TradingModel:
    def __init__(self, sequence_length, n_features):
        self.model = self._create_model((sequence_length, n_features))

    def _create_model(self, input_shape):
        # Enable mixed precision training for better performance
        tf.keras.mixed_precision.set_global_policy('mixed_float16')

        model = Sequential([
            LSTM(64, input_shape=input_shape, return_sequences=True),
            Dropout(0.2),
            LSTM(64, return_sequences=False),
            Dense(32, activation='relu'),
            Dropout(0.2),
            Dense(1, activation='tanh')
        ])
        model.compile(optimizer='adam', loss='mse')
        return model

    def train(self, X_train, y_train, epochs=20, batch_size=32):
        # Add early stopping to prevent overfitting
        early_stopping = tf.keras.callbacks.EarlyStopping(
            monitor='loss',
            patience=5,
            restore_best_weights=True
        )

        self.model.fit(
            X_train,
            y_train,
            epochs=epochs,
            batch_size=batch_size,
            callbacks=[early_stopping],
            validation_split=0.1,
            verbose=1
        )

    def predict(self, X_test, threshold_buy=0, threshold_sell=0):
        y_pred = self.model.predict(X_test, verbose=0)
        print(y_pred)
        return np.where(y_pred > threshold_buy, 1, np.where(y_pred < threshold_sell, -1, 0))

class MockBroker:
    def __init__(self, initial_balance: float, price_data: dict):
        self.initial_balance = initial_balance
        self.balance = initial_balance
        self.price_data = price_data
        self.holdings = {symbol: 0 for symbol in price_data.keys()}
        self.current_day = 0
        self.transaction_history = []

    def get_current_price(self, symbol: str) -> float:
        return self.price_data[symbol].iloc[self.current_day]['close']

    def buy(self, symbol: str, quantity: int) -> bool:
        cost = self.get_current_price(symbol) * quantity
        if cost > self.balance:
            return False
        self.balance -= cost
        self.holdings[symbol] += quantity
        self.transaction_history.append({
            'day': self.current_day,
            'symbol': symbol,
            'action': 'buy',
            'quantity': quantity,
            'price': self.get_current_price(symbol)
        })
        return True

    def sell(self, symbol: str, quantity: int) -> bool:
        if self.holdings[symbol] < quantity:
            return False
        proceeds = self.get_current_price(symbol) * quantity
        self.balance += proceeds
        self.holdings[symbol] -= quantity
        self.transaction_history.append({
            'day': self.current_day,
            'symbol': symbol,
            'action': 'sell',
            'quantity': quantity,
            'price': self.get_current_price(symbol)
        })
        return True

    def get_net_worth(self) -> float:
        holdings_value = sum(
            self.get_current_price(symbol) * quantity
            for symbol, quantity in self.holdings.items()
        )
        return self.balance + holdings_value

    def get_performance_metrics(self):
        final_worth = self.get_net_worth()
        total_return = ((final_worth - self.initial_balance) / self.initial_balance) * 100
        return {
            'initial_balance': self.initial_balance,
            'final_balance': self.balance,
            'final_net_worth': final_worth,
            'total_return_percent': total_return,
            'total_trades': len(self.transaction_history)
        }

    def next_day(self):
        self.current_day += 1

def main():
    # Initialize components
    data_loader = DataLoader(DATA_DIR)
    dataframe_dict = data_loader.load_data()

    # Training parameters
    train_days = 900
    sequence_length = 30

    # Store predictions and test data
    predictions = {}
    test_data_dict = {}

    # Train models for each symbol
    for symbol, df in dataframe_dict.items():
        print(f"\nProcessing {symbol}...")

        # Prepare data
        X_train, y_train, X_test, y_test, test_data = data_loader.prepare_data(
            df, train_days, sequence_length
        )
        test_data_dict[symbol] = test_data

        # Create and train model
        model = TradingModel(sequence_length, X_train.shape[-1])
        model.train(X_train, y_train)

        # Generate predictions
        predictions[symbol] = model.predict(X_test)

    # Initialize and run broker simulation
    broker = MockBroker(10000, test_data_dict)

    # Simulation loop
    print("\nStarting trading simulation...")
    for i in range(len(next(iter(test_data_dict.values())))):
        for symbol in predictions.keys():
            broker.current_day = i
            if i < len(predictions[symbol]):
                action = predictions[symbol][i]
                if action == 1:
                    broker.buy(symbol, 10)
                elif action == -1:
                    broker.sell(symbol, 10)

    # Print final results
    metrics = broker.get_performance_metrics()
    print("\nTrading Simulation Results:")
    print(f"Initial Balance: ${metrics['initial_balance']:,.2f}")
    print(f"Final Balance: ${metrics['final_balance']:,.2f}")
    print(f"Final Net Worth: ${metrics['final_net_worth']:,.2f}")
    print(f"Total Return: {metrics['total_return_percent']:.2f}%")
    print(f"Total Trades: {metrics['total_trades']}")

if __name__ == "__main__":
    main()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
          symbol     open     high      low    close      volume       MACD  \
0    NSE:DRREDDY  1010.00  1026.90  1006.00  1014.57   6803005.0   0.000000   
1    NSE:DRREDDY  1016.00  1052.57  1015.63  1045.75  18525665.0   2.487293   
2    NSE:DRREDDY  1048.60  1054.84   992.41  1013.71   9061285.0   1.851785   
3    NSE:DRREDDY  1021.54  1035.00   987.27  1032.36   7764120.0   2.820526   
4    NSE:DRREDDY  1032.29  1047.74  1026.25  1044.82   4062350.0   4.541328   
..           ...      ...      ...      ...      ...         ...        ...   
995  NSE:DRREDDY  1362.00  1367.00  1330.30  1341.35   3740109.0  17.364529   
996  NSE:DRREDDY  1347.00  1365.00  1336.20  1350.90   2587142.0  21.468928   
997  NSE:DRREDDY  1350.90  1360.20  1342.75  1355.15   1531359.0  24.778997   
998  NSE:DRREDDY  1363.05  1398.25  1345.50  1389.45   3656253.0  29.826156   
99

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: nan - val_loss: 0.0343
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0344
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0344
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0346
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: nan - val_loss: 0.0340
[[0.00283 ]
 [0.003937]
 [0.00475 ]
 [0.005714]
 [0.006874]
 [0.007812]
 [0.00865 ]
 [0.00908 ]
 [0.00916 ]
 [0.00953 ]
 [0.00967 ]
 [0.00924 ]
 [0.00836 ]
 [0.007248]
 [0.006504]
 [0.00603 ]
 [0.00571 ]
 [0.005554]
 [0.00546 ]
 [0.00514 ]
 [0.005142]
 [0.004997]
 [0.004963]
 [0.004707]
 [0.004337]
 [0.003914]
 [0.003555]
 [0.003218]
 [0.00311 ]
 [0.002886]
 [0.002638]
 [0.002863]
 [0.003258]
 [0.003975]
 [0.004765]
 [0.005882]
 [0.006783]
 [0.007454]
 [0.00805 ]
 [0.008354]
 [0.00841 ]
 [0.00827 ]
 [0.00803 ]
 [0.00825 ]
 [0.00877 ]
 [0.00953 ]
 [0.01037 ]
 [0.01126 ]
 [0.01194 ]
 [0.01218 ]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0023
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 3.1683e-04
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 1.6231e-04
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 3.0531e-04
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 1.5433e-04
[[0.0406 ]
 [0.04108]
 [0.04144]
 [0.04245]
 [0.0439 ]
 [0.04578]
 [0.0479 ]
 [0.05008]
 [0.05194]
 [0.05322]
 [0.05426]
 [0.05475]
 [0.05447]
 [0.05377]
 [0.0531 ]
 [0.05234]
 [0.05173]
 [0.05075]
 [0.0495 ]
 [0.04803]
 [0.0463 ]
 [0.0441 ]
 [0.042  ]
 [0.04034]
 [0.0389 ]
 [0.0381 ]
 [0.03754]
 [0.037  ]
 [0.03632]
 [0.0356 ]
 [0.03488]
 [0.03424]
 [0.03372]
 [0.03336]
 [0.0339 ]
 [0.03494]
 [0.0358 ]
 [0.03644]
 [0.03757]
 [0.0388 ]
 [0.03955]
 [0.04028]
 [0.04092]
 [0.0416 ]
 [0.04224]
 [0.04337]
 [0.04477]
 [0.0457 ]
 [0.04623]
 [0.04617]
 [0.0459 ]
 [0.04565]
 [0.0454 ]
 [0.0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: nan - val_loss: 0.0687
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0708
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0694
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: nan - val_loss: 0.0688
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: nan - val_loss: 0.0689
[[-5.6992e-03]
 [-6.4316e-03]
 [-7.2136e-03]
 [-8.1482e-03]
 [-9.1324e-03]
 [-1.0109e-02]
 [-1.1024e-02]
 [-1.1543e-02]
 [-1.1932e-02]
 [-1.2291e-02]
 [-1.2642e-02]
 [-1.3092e-02]
 [-1.3680e-02]
 [-1.4252e-02]
 [-1.4565e-02]
 [-1.4725e-02]
 [-1.4633e-02]
 [-1.4297e-02]
 [-1.3611e-02]
 [-1.2733e-02]
 [-1.1734e-02]
 [-1.0834e-02]
 [-1.0071e-02]
 [-9.3765e-03]
 [-8.6670e-03]
 [-7.8430e-03]
 [-6.8893e-03]
 [-5.7602e-03]
 [-4.2610e-03]
 [-2.3346e-03]
 [-5.4359e-05]
 [ 2.4529e-03]
 [ 4.9667e-03]
 [ 6.0806e-03]
 [ 6.9313e-03]
 [ 7.2746e-03]
 [ 7.4196e-03]
 [ 7.6027e-03]
 [ 7.8201e-03]
 [ 7.9880e-03]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0238
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0247
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0233
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0231
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0231
[[-0.02066 ]
 [-0.02034 ]
 [-0.0201  ]
 [-0.01947 ]
 [-0.01898 ]
 [-0.01854 ]
 [-0.018   ]
 [-0.0169  ]
 [-0.01585 ]
 [-0.01543 ]
 [-0.0156  ]
 [-0.01726 ]
 [-0.0191  ]
 [-0.0205  ]
 [-0.02124 ]
 [-0.02173 ]
 [-0.02182 ]
 [-0.02203 ]
 [-0.0217  ]
 [-0.0212  ]
 [-0.02074 ]
 [-0.02051 ]
 [-0.01993 ]
 [-0.01888 ]
 [-0.01768 ]
 [-0.01616 ]
 [-0.01456 ]
 [-0.01309 ]
 [-0.01159 ]
 [-0.00992 ]
 [-0.008644]
 [-0.00782 ]
 [-0.007427]
 [-0.007557]
 [-0.00786 ]
 [-0.00814 ]
 [-0.00911 ]
 [-0.01065 ]
 [-0.01206 ]
 [-0.013306]
 [-0.0146  ]
 [-0.01509 ]
 [-0.01552 ]
 [-0.01625 ]
 [-0.01704 ]
 [-0.0177  ]
 [-0.0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0233
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0228
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0227
[[0.01458 ]
 [0.01476 ]
 [0.014854]
 [0.0149  ]
 [0.01492 ]
 [0.01499 ]
 [0.015144]
 [0.01526 ]
 [0.015434]
 [0.01557 ]
 [0.0157  ]
 [0.0158  ]
 [0.01558 ]
 [0.01527 ]
 [0.014946]
 [0.01472 ]
 [0.01464 ]
 [0.01453 ]
 [0.01456 ]
 [0.01468 ]
 [0.0147  ]
 [0.01469 ]
 [0.01464 ]
 [0.01467 ]
 [0.01471 ]
 [0.01476 ]
 [0.014824]
 [0.014915]
 [0.01492 ]
 [0.01503 ]
 [0.0152  ]
 [0.01528 ]
 [0.01523 ]
 [0.01508 ]
 [0.015   ]
 [0.01496 ]
 [0.01503 ]
 [0.015114]
 [0.0152  ]
 [0.01539 ]
 [0.01546 ]
 [0.015594]
 [0.015526]
 [0.01541 ]
 [0.01527 ]
 [0.01523 ]
 [0.01536 ]
 [0.01562 ]
 [0.0159  ]
 [0.01608 ]
 [0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: nan - val_loss: 0.0379
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0344
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0344
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0344
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: nan - val_loss: 0.0341
[[0.0607 ]
 [0.05997]
 [0.059  ]
 [0.05753]
 [0.05624]
 [0.05515]
 [0.05453]
 [0.05414]
 [0.05377]
 [0.0537 ]
 [0.0536 ]
 [0.05273]
 [0.05106]
 [0.04977]
 [0.0486 ]
 [0.04706]
 [0.04562]
 [0.04425]
 [0.0429 ]
 [0.04156]
 [0.04007]
 [0.03802]
 [0.03595]
 [0.03406]
 [0.03235]
 [0.03204]
 [0.03278]
 [0.03345]
 [0.0342 ]
 [0.03482]
 [0.0351 ]
 [0.03506]
 [0.03525]
 [0.03574]
 [0.03665]
 [0.038  ]
 [0.03912]
 [0.04044]
 [0.04178]
 [0.04187]
 [0.04117]
 [0.0405 ]
 [0.04004]
 [0.03918]
 [0.03827]
 [0.03827]
 [0.0385 ]
 [0.03885]
 [0.03912]
 [0.03882]
 [0.03867]
 [0.03876]
 [0.03925]
 [0.0404 ]
 [0.042

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0463
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0458
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0461
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0458
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0457
[[0.0318 ]
 [0.0337 ]
 [0.03662]
 [0.04044]
 [0.04382]
 [0.04672]
 [0.04898]
 [0.05008]
 [0.0501 ]
 [0.04953]
 [0.0483 ]
 [0.04706]
 [0.04617]
 [0.04565]
 [0.0453 ]
 [0.04453]
 [0.04367]
 [0.04282]
 [0.04205]
 [0.04138]
 [0.0409 ]
 [0.04095]
 [0.04126]
 [0.04166]
 [0.04208]
 [0.0424 ]
 [0.04257]
 [0.04276]
 [0.0426 ]
 [0.04276]
 [0.04315]
 [0.04388]
 [0.04453]
 [0.04514]
 [0.0454 ]
 [0.04526]
 [0.04504]
 [0.04495]
 [0.04486]
 [0.0449 ]
 [0.04504]
 [0.04526]
 [0.04572]
 [0.04596]
 [0.0459 ]
 [0.04523]
 [0.04407]
 [0.04245]
 [0.04068]
 [0.03906]
 [0.03732]
 [0.03513]
 [0.03265]
 [0.03012]
 [0.02895

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0353
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0346
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0345
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0353
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
[[-0.03442 ]
 [-0.0362  ]
 [-0.03787 ]
 [-0.0395  ]
 [-0.04092 ]
 [-0.0417  ]
 [-0.04202 ]
 [-0.0423  ]
 [-0.04263 ]
 [-0.04318 ]
 [-0.0436  ]
 [-0.04385 ]
 [-0.04395 ]
 [-0.04404 ]
 [-0.04398 ]
 [-0.0437  ]
 [-0.04333 ]
 [-0.04288 ]
 [-0.04236 ]
 [-0.04172 ]
 [-0.04108 ]
 [-0.04034 ]
 [-0.03967 ]
 [-0.0391  ]
 [-0.03836 ]
 [-0.03763 ]
 [-0.03687 ]
 [-0.03592 ]
 [-0.03497 ]
 [-0.034   ]
 [-0.03296 ]
 [-0.03198 ]
 [-0.02975 ]
 [-0.02788 ]
 [-0.0261  ]
 [-0.02429 ]
 [-0.02264 ]
 [-0.02086 ]
 [-0.01906 ]
 [-0.01758 ]
 [-0.0165  ]
 [-0.01561 ]
 [-0.015045]
 [-0.01492 ]
 [-0.015015]
 [-0.0148  ]
 [-0.0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0231
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0235
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0241
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0228
[[0.014725]
 [0.014694]
 [0.014404]
 [0.014175]
 [0.013855]
 [0.013626]
 [0.01366 ]
 [0.013794]
 [0.01404 ]
 [0.01422 ]
 [0.014435]
 [0.01456 ]
 [0.01466 ]
 [0.0148  ]
 [0.01492 ]
 [0.015   ]
 [0.01521 ]
 [0.015594]
 [0.01604 ]
 [0.01663 ]
 [0.01733 ]
 [0.01819 ]
 [0.01884 ]
 [0.01956 ]
 [0.02023 ]
 [0.02104 ]
 [0.02188 ]
 [0.02191 ]
 [0.0214  ]
 [0.02014 ]
 [0.019   ]
 [0.01892 ]
 [0.0194  ]
 [0.02002 ]
 [0.0205  ]
 [0.02061 ]
 [0.02026 ]
 [0.02016 ]
 [0.02078 ]
 [0.02171 ]
 [0.02269 ]
 [0.0236  ]
 [0.02435 ]
 [0.02498 ]
 [0.02556 ]
 [0.02559 ]
 [0.0253  ]
 [0.02477 ]
 [0.02406 ]
 [0.02333 ]
 [0.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: nan - val_loss: 0.0237
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0227
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0230
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0230
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
[[0.02063]
 [0.02094]
 [0.0214 ]
 [0.02185]
 [0.0224 ]
 [0.023  ]
 [0.02359]
 [0.02412]
 [0.02449]
 [0.02464]
 [0.02477]
 [0.02475]
 [0.02469]
 [0.02477]
 [0.02498]
 [0.02513]
 [0.02553]
 [0.02602]
 [0.02654]
 [0.02724]
 [0.02798]
 [0.02885]
 [0.02977]
 [0.0306 ]
 [0.03156]
 [0.03262]
 [0.03387]
 [0.0352 ]
 [0.03638]
 [0.03757]
 [0.03857]
 [0.0396 ]
 [0.04056]
 [0.04147]
 [0.04245]
 [0.04294]
 [0.04318]
 [0.04343]
 [0.04367]
 [0.044  ]
 [0.0443 ]
 [0.0446 ]
 [0.04474]
 [0.0447 ]
 [0.04474]
 [0.04474]
 [0.0447 ]
 [0.0446 ]
 [0.04456]
 [0.04443]
 [0.04434]
 [0.04422]
 [0.04413]
 [0.04395]
 [0.0437 ]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: nan - val_loss: 6.0890e-04
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 1.2011e-05
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 9.5973e-06
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: nan - val_loss: 1.7620e-04
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 1.7293e-06
[[0.0397 ]
 [0.04034]
 [0.0409 ]
 [0.04105]
 [0.04047]
 [0.03967]
 [0.03912]
 [0.03802]
 [0.03714]
 [0.03726]
 [0.03766]
 [0.03876]
 [0.04022]
 [0.0418 ]
 [0.04245]
 [0.04257]
 [0.0427 ]
 [0.04254]
 [0.0425 ]
 [0.04254]
 [0.04312]
 [0.04422]
 [0.0453 ]
 [0.04648]
 [0.04773]
 [0.04877]
 [0.04977]
 [0.0507 ]
 [0.05225]
 [0.05392]
 [0.05545]
 [0.05716]
 [0.05862]
 [0.05933]
 [0.0595 ]
 [0.0584 ]
 [0.05774]
 [0.05756]
 [0.05756]
 [0.05798]
 [0.0632 ]
 [0.0704 ]
 [0.0766 ]
 [0.08105]
 [0.08527]
 [0.0896 ]
 [0.09357]
 [0.0961 ]
 [0.09796]
 [0.0991 ]
 [0.09973]
 [0.0994 ]
 [0.0967 ]


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0345
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0347
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0344
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0344
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
[[-0.00933 ]
 [-0.009285]
 [-0.009186]
 [-0.00917 ]
 [-0.00921 ]
 [-0.00933 ]
 [-0.00939 ]
 [-0.00956 ]
 [-0.00978 ]
 [-0.0099  ]
 [-0.01014 ]
 [-0.010376]
 [-0.01052 ]
 [-0.010666]
 [-0.010826]
 [-0.0111  ]
 [-0.01133 ]
 [-0.011566]
 [-0.01186 ]
 [-0.012085]
 [-0.01226 ]
 [-0.01248 ]
 [-0.01262 ]
 [-0.01283 ]
 [-0.01293 ]
 [-0.013145]
 [-0.01335 ]
 [-0.013435]
 [-0.01349 ]
 [-0.01342 ]
 [-0.01335 ]
 [-0.01313 ]
 [-0.012764]
 [-0.01255 ]
 [-0.012436]
 [-0.01245 ]
 [-0.01248 ]
 [-0.012535]
 [-0.01267 ]
 [-0.01268 ]
 [-0.01265 ]
 [-0.012596]
 [-0.01255 ]
 [-0.01262 ]
 [-0.01277 ]
 [-0.01317 ]
 [-0.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0460
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0460
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0461
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0461
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0460
[[ 3.6850e-03]
 [ 2.9583e-03]
 [ 2.3785e-03]
 [ 2.0504e-03]
 [ 1.6174e-03]
 [ 1.1425e-03]
 [ 5.3740e-04]
 [ 8.0824e-05]
 [-7.5197e-04]
 [-2.2049e-03]
 [-3.8433e-03]
 [-5.7449e-03]
 [-7.7324e-03]
 [-9.6741e-03]
 [-1.1353e-02]
 [-1.2680e-02]
 [-1.3603e-02]
 [-1.4503e-02]
 [-1.5060e-02]
 [-1.4992e-02]
 [-1.4458e-02]
 [-1.4664e-02]
 [-1.4641e-02]
 [-1.3557e-02]
 [-1.1551e-02]
 [-9.0714e-03]
 [-6.1340e-03]
 [-2.9869e-03]
 [ 1.4472e-04]
 [ 2.3060e-03]
 [ 4.1885e-03]
 [ 5.6763e-03]
 [ 6.6032e-03]
 [ 6.9046e-03]
 [ 6.8893e-03]
 [ 6.7215e-03]
 [ 6.0844e-03]
 [ 5.1346e-03]
 [ 4.0245e-03]
 [ 2.9659e-03]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: nan - val_loss: 0.0339
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0354
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 0.0349
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0356
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0353
[[-0.01826  ]
 [-0.01942  ]
 [-0.02098  ]
 [-0.0228   ]
 [-0.02481  ]
 [-0.02682  ]
 [-0.02905  ]
 [-0.03165  ]
 [-0.03418  ]
 [-0.03622  ]
 [-0.03787  ]
 [-0.03897  ]
 [-0.03946  ]
 [-0.0392   ]
 [-0.03824  ]
 [-0.03644  ]
 [-0.0339   ]
 [-0.03082  ]
 [-0.02725  ]
 [-0.02444  ]
 [-0.02121  ]
 [-0.01768  ]
 [-0.01375  ]
 [-0.00935  ]
 [-0.005222 ]
 [-0.002155 ]
 [ 0.000807 ]
 [ 0.003695 ]
 [ 0.005802 ]
 [ 0.00594  ]
 [ 0.00642  ]
 [ 0.006588 ]
 [ 0.006237 ]
 [ 0.005142 ]
 [ 0.003883 ]
 [ 0.001521 ]
 [-0.0002394]
 [-0.001185 ]
 [-0.001731 ]
 [-0.001995 ]
 [-0.002113 ]
 [-0.002087 ]
 [-0.001903 ]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: nan - val_loss: 0.0129
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0121
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0113
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0113
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0114
[[-0.03906]
 [-0.0387 ]
 [-0.03824]
 [-0.03775]
 [-0.03735]
 [-0.03677]
 [-0.03607]
 [-0.0352 ]
 [-0.03427]
 [-0.03354]
 [-0.03275]
 [-0.03204]
 [-0.0313 ]
 [-0.0305 ]
 [-0.02971]
 [-0.02896]
 [-0.02872]
 [-0.0285 ]
 [-0.02837]
 [-0.02835]
 [-0.02844]
 [-0.02861]
 [-0.02884]
 [-0.02893]
 [-0.02895]
 [-0.02878]
 [-0.02849]
 [-0.02838]
 [-0.0281 ]
 [-0.02777]
 [-0.02739]
 [-0.02702]
 [-0.0265 ]
 [-0.02571]
 [-0.02472]
 [-0.02348]
 [-0.02196]
 [-0.02043]
 [-0.01926]
 [-0.0185 ]
 [-0.01796]
 [-0.01761]
 [-0.01778]
 [-0.01823]
 [-0.01875]
 [-0.0193 ]
 [-0.02   ]
 [-0.02089]
 [-0.0219 ]
 [-0.0229 ]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - loss: nan - val_loss: 0.0461
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0460
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0460
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0460
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0460
[[-0.01595 ]
 [-0.01584 ]
 [-0.01569 ]
 [-0.015564]
 [-0.015366]
 [-0.01517 ]
 [-0.015015]
 [-0.01474 ]
 [-0.01462 ]
 [-0.01462 ]
 [-0.01463 ]
 [-0.01468 ]
 [-0.01474 ]
 [-0.01457 ]
 [-0.01437 ]
 [-0.01422 ]
 [-0.0139  ]
 [-0.013596]
 [-0.01309 ]
 [-0.012505]
 [-0.01198 ]
 [-0.011505]
 [-0.01098 ]
 [-0.010445]
 [-0.00989 ]
 [-0.00933 ]
 [-0.008766]
 [-0.008224]
 [-0.00773 ]
 [-0.007217]
 [-0.00685 ]
 [-0.006638]
 [-0.00663 ]
 [-0.006783]
 [-0.006943]
 [-0.007057]
 [-0.007225]
 [-0.00734 ]
 [-0.00744 ]
 [-0.007538]
 [-0.00756 ]
 [-0.007706]
 [-0.00779 ]
 [-0.00782 ]
 [-0.007797]
 [-0.007538]
 [-

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0357
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0346
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0345
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0344
[[-0.03464 ]
 [-0.03506 ]
 [-0.0355  ]
 [-0.036   ]
 [-0.03653 ]
 [-0.0372  ]
 [-0.0378  ]
 [-0.03842 ]
 [-0.03882 ]
 [-0.03906 ]
 [-0.0393  ]
 [-0.03943 ]
 [-0.03934 ]
 [-0.0392  ]
 [-0.03897 ]
 [-0.0386  ]
 [-0.0382  ]
 [-0.03772 ]
 [-0.0372  ]
 [-0.03662 ]
 [-0.03583 ]
 [-0.03485 ]
 [-0.03384 ]
 [-0.0329  ]
 [-0.03192 ]
 [-0.03099 ]
 [-0.03008 ]
 [-0.02924 ]
 [-0.02852 ]
 [-0.02795 ]
 [-0.02748 ]
 [-0.02707 ]
 [-0.02672 ]
 [-0.02643 ]
 [-0.02614 ]
 [-0.02588 ]
 [-0.02557 ]
 [-0.0252  ]
 [-0.02464 ]
 [-0.02393 ]
 [-0.02315 ]
 [-0.02231 ]
 [-0.02092 ]
 [-0.0184  ]
 [-0.015366]
 [-0.01229 ]
 [-0.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 62ms/step - loss: nan - val_loss: 0.0469
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0458
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0458
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0466
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0457
[[-0.03226]
 [-0.03253]
 [-0.0326 ]
 [-0.03232]
 [-0.032  ]
 [-0.03174]
 [-0.03162]
 [-0.03143]
 [-0.0314 ]
 [-0.03198]
 [-0.03278]
 [-0.03394]
 [-0.03497]
 [-0.03577]
 [-0.03622]
 [-0.03632]
 [-0.03635]
 [-0.0364 ]
 [-0.0366 ]
 [-0.03665]
 [-0.03662]
 [-0.0367 ]
 [-0.03674]
 [-0.03635]
 [-0.0357 ]
 [-0.03476]
 [-0.03363]
 [-0.03247]
 [-0.0312 ]
 [-0.03017]
 [-0.02847]
 [-0.02681]
 [-0.02509]
 [-0.02347]
 [-0.02191]
 [-0.02031]
 [-0.01888]
 [-0.01794]
 [-0.01726]
 [-0.01698]
 [-0.01695]
 [-0.01697]
 [-0.017  ]
 [-0.01682]
 [-0.01692]
 [-0.01668]
 [-0.01668]
 [-0.01692]
 [-0.01729]
 [-0.0182 ]
 [-0.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: nan - val_loss: 0.1035
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.1039
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.1043
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.1053
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.1030
[[0.010796]
 [0.0103  ]
 [0.00991 ]
 [0.00964 ]
 [0.009605]
 [0.00958 ]
 [0.00972 ]
 [0.01017 ]
 [0.01085 ]
 [0.01122 ]
 [0.01143 ]
 [0.01102 ]
 [0.01034 ]
 [0.00942 ]
 [0.00872 ]
 [0.00812 ]
 [0.007713]
 [0.007446]
 [0.007347]
 [0.00923 ]
 [0.0118  ]
 [0.01438 ]
 [0.0167  ]
 [0.01889 ]
 [0.02084 ]
 [0.02264 ]
 [0.02444 ]
 [0.02606 ]
 [0.02731 ]
 [0.02843 ]
 [0.02937 ]
 [0.02989 ]
 [0.03029 ]
 [0.03035 ]
 [0.03026 ]
 [0.03026 ]
 [0.0301  ]
 [0.02968 ]
 [0.02928 ]
 [0.02888 ]
 [0.02855 ]
 [0.02855 ]
 [0.02864 ]
 [0.0287  ]
 [0.02835 ]
 [0.02867 ]
 [0.02943 ]
 [0.03053 ]
 [0.03099 ]
 [0.03072 ]
 [0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0688
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0689
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0689
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0690
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0684
[[-0.01726]
 [-0.01762]
 [-0.01807]
 [-0.01872]
 [-0.01956]
 [-0.02043]
 [-0.02142]
 [-0.02249]
 [-0.02342]
 [-0.02415]
 [-0.02483]
 [-0.02513]
 [-0.02515]
 [-0.02477]
 [-0.02435]
 [-0.0236 ]
 [-0.02295]
 [-0.02191]
 [-0.02112]
 [-0.02045]
 [-0.01996]
 [-0.01947]
 [-0.01912]
 [-0.01918]
 [-0.01929]
 [-0.01968]
 [-0.02022]
 [-0.02084]
 [-0.02136]
 [-0.02203]
 [-0.02245]
 [-0.02284]
 [-0.02313]
 [-0.02327]
 [-0.02364]
 [-0.02388]
 [-0.0241 ]
 [-0.02426]
 [-0.02454]
 [-0.02454]
 [-0.02428]
 [-0.02394]
 [-0.02348]
 [-0.02321]
 [-0.02303]
 [-0.02289]
 [-0.0231 ]
 [-0.02348]
 [-0.02406]
 [-0.02461]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: nan - val_loss: 0.0115
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: nan - val_loss: 0.0113
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0115
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: nan - val_loss: 0.0115
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0115
[[-6.9885e-03]
 [-6.8703e-03]
 [-6.8016e-03]
 [-6.9351e-03]
 [-7.1411e-03]
 [-7.1716e-03]
 [-7.1297e-03]
 [-7.0915e-03]
 [-6.9771e-03]
 [-6.8130e-03]
 [-6.6147e-03]
 [-6.2866e-03]
 [-5.8784e-03]
 [-5.5466e-03]
 [-5.2567e-03]
 [-4.9515e-03]
 [-4.6616e-03]
 [-4.3488e-03]
 [-4.0016e-03]
 [-3.7117e-03]
 [-3.4580e-03]
 [-3.0842e-03]
 [-2.6684e-03]
 [-2.2621e-03]
 [-1.9054e-03]
 [-1.5907e-03]
 [-1.1559e-03]
 [-8.5545e-04]
 [-8.1158e-04]
 [-8.7261e-04]
 [-1.0405e-03]
 [-1.1406e-03]
 [-1.2093e-03]
 [-1.2531e-03]
 [-1.2360e-03]
 [-1.1616e-03]
 [-1.0452e-03]
 [-1.0099e-03]
 [-9.8324e-04]
 [-9.0218e-04]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0457
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0457
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0458
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0458
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0457
[[ 3.3188e-03]
 [ 3.1929e-03]
 [ 3.5515e-03]
 [ 4.7646e-03]
 [ 5.8403e-03]
 [ 6.3095e-03]
 [ 6.4011e-03]
 [ 6.3057e-03]
 [ 5.4588e-03]
 [ 4.1618e-03]
 [ 2.9602e-03]
 [ 1.8969e-03]
 [ 1.1311e-03]
 [ 3.8981e-04]
 [-4.9591e-05]
 [-2.8801e-04]
 [-1.5545e-04]
 [-5.7220e-05]
 [-7.2002e-05]
 [-3.5095e-04]
 [-9.0790e-04]
 [-1.6127e-03]
 [-2.3308e-03]
 [-3.1815e-03]
 [-3.9330e-03]
 [-4.2343e-03]
 [-4.1161e-03]
 [-3.5553e-03]
 [-2.7466e-03]
 [-1.6928e-03]
 [-7.8964e-04]
 [ 1.2875e-05]
 [ 7.7343e-04]
 [ 1.4381e-03]
 [ 1.9779e-03]
 [ 2.3861e-03]
 [ 2.5406e-03]
 [ 2.6131e-03]
 [ 2.7275e-03]
 [ 2.8191e-03]
 [ 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0463
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0459
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 0.0460
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0460
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0460
[[0.01341 ]
 [0.01342 ]
 [0.01342 ]
 [0.01356 ]
 [0.01385 ]
 [0.01433 ]
 [0.01486 ]
 [0.01552 ]
 [0.0162  ]
 [0.01639 ]
 [0.01643 ]
 [0.01631 ]
 [0.01616 ]
 [0.01585 ]
 [0.01569 ]
 [0.015564]
 [0.01547 ]
 [0.01538 ]
 [0.01518 ]
 [0.015   ]
 [0.01482 ]
 [0.01466 ]
 [0.01457 ]
 [0.01451 ]
 [0.014435]
 [0.014496]
 [0.014694]
 [0.01494 ]
 [0.01518 ]
 [0.01543 ]
 [0.015396]
 [0.015335]
 [0.01521 ]
 [0.015045]
 [0.01486 ]
 [0.01494 ]
 [0.015015]
 [0.015076]
 [0.0152  ]
 [0.01538 ]
 [0.01549 ]
 [0.0158  ]
 [0.01569 ]
 [0.01555 ]
 [0.015015]
 [0.01451 ]
 [0.01427 ]
 [0.014145]
 [0.01422 ]
 [0.01436 ]
 [0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0354
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0350
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0350
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
[[-0.02309]
 [-0.02321]
 [-0.02312]
 [-0.02283]
 [-0.02232]
 [-0.02165]
 [-0.02083]
 [-0.0199 ]
 [-0.01929]
 [-0.01866]
 [-0.01811]
 [-0.01778]
 [-0.0176 ]
 [-0.01785]
 [-0.01819]
 [-0.01851]
 [-0.01886]
 [-0.01927]
 [-0.0197 ]
 [-0.02011]
 [-0.02058]
 [-0.02126]
 [-0.02213]
 [-0.02301]
 [-0.02388]
 [-0.02466]
 [-0.0253 ]
 [-0.02576]
 [-0.02644]
 [-0.02704]
 [-0.0276 ]
 [-0.0282 ]
 [-0.02876]
 [-0.0295 ]
 [-0.03029]
 [-0.03114]
 [-0.03207]
 [-0.03308]
 [-0.03406]
 [-0.03543]
 [-0.03702]
 [-0.0389 ]
 [-0.04123]
 [-0.04398]
 [-0.04712]
 [-0.04996]
 [-0.05243]
 [-0.05466]
 [-0.0563 ]
 [-0.0577 ]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0239
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: nan - val_loss: 0.0227
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0235
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0227
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
[[-0.0391 ]
 [-0.03857]
 [-0.03812]
 [-0.0378 ]
 [-0.0376 ]
 [-0.03748]
 [-0.0374 ]
 [-0.03723]
 [-0.03714]
 [-0.03735]
 [-0.03775]
 [-0.03836]
 [-0.03906]
 [-0.0399 ]
 [-0.04068]
 [-0.04132]
 [-0.04196]
 [-0.04254]
 [-0.04285]
 [-0.04285]
 [-0.04282]
 [-0.04282]
 [-0.04236]
 [-0.04156]
 [-0.04117]
 [-0.04083]
 [-0.0406 ]
 [-0.04034]
 [-0.04016]
 [-0.04   ]
 [-0.03998]
 [-0.04004]
 [-0.0402 ]
 [-0.04028]
 [-0.04044]
 [-0.04047]
 [-0.0406 ]
 [-0.0407 ]
 [-0.04074]
 [-0.04068]
 [-0.0406 ]
 [-0.04056]
 [-0.0405 ]
 [-0.04053]
 [-0.0405 ]
 [-0.0404 ]
 [-0.04028]
 [-0.03992]
 [-0.0397 ]
 [-0.03955]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: nan - val_loss: 0.0114
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: nan - val_loss: 0.0137
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0114
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: nan - val_loss: 0.0115
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0117
[[ 0.00764  ]
 [ 0.00804  ]
 [ 0.00831  ]
 [ 0.008514 ]
 [ 0.008606 ]
 [ 0.00861  ]
 [ 0.00895  ]
 [ 0.00952  ]
 [ 0.00998  ]
 [ 0.01039  ]
 [ 0.01073  ]
 [ 0.01019  ]
 [ 0.008835 ]
 [ 0.007427 ]
 [ 0.006172 ]
 [ 0.004833 ]
 [ 0.003414 ]
 [ 0.001869 ]
 [ 0.000855 ]
 [ 0.0002351]
 [-0.0001526]
 [-0.000656 ]
 [-0.001738 ]
 [-0.00301  ]
 [-0.004456 ]
 [-0.005768 ]
 [-0.006924 ]
 [-0.007645 ]
 [-0.00825  ]
 [-0.0096   ]
 [-0.010826 ]
 [-0.011635 ]
 [-0.01234  ]
 [-0.01314  ]
 [-0.014015 ]
 [-0.01419  ]
 [-0.01425  ]
 [-0.01407  ]
 [-0.01366  ]
 [-0.0132   ]
 [-0.01311  ]
 [-0.012405 ]
 [-0.01108  ]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: nan - val_loss: 0.0116
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0118
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0113
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0113
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0113
[[-1.1078e-02]
 [-1.0117e-02]
 [-8.7128e-03]
 [-7.0152e-03]
 [-5.2795e-03]
 [-4.7302e-03]
 [-3.9978e-03]
 [-3.2139e-03]
 [-2.3346e-03]
 [-1.5078e-03]
 [-7.1430e-04]
 [-1.9073e-05]
 [ 2.3651e-04]
 [ 3.0899e-04]
 [ 3.6812e-04]
 [ 4.1771e-04]
 [ 5.1308e-04]
 [ 5.8365e-04]
 [ 7.8011e-04]
 [ 1.0204e-03]
 [ 1.3046e-03]
 [ 1.6975e-03]
 [ 2.0714e-03]
 [ 2.4796e-03]
 [ 2.7542e-03]
 [ 3.0785e-03]
 [ 3.4218e-03]
 [ 3.7155e-03]
 [ 4.0283e-03]
 [ 4.2877e-03]
 [ 4.5853e-03]
 [ 4.6883e-03]
 [ 4.8256e-03]
 [ 5.0049e-03]
 [ 5.2834e-03]
 [ 5.7297e-03]
 [ 6.2561e-03]
 [ 6.7215e-03]
 [ 7.2250e-03]
 [ 6.4240e-03]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 1.3779e-04
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 1.3399e-04
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 2.0884e-04
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 1.2736e-04
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 8.3527e-04
[[-0.013374]
 [-0.01414 ]
 [-0.01498 ]
 [-0.01593 ]
 [-0.01694 ]
 [-0.01805 ]
 [-0.01923 ]
 [-0.02057 ]
 [-0.02188 ]
 [-0.0232  ]
 [-0.0244  ]
 [-0.02547 ]
 [-0.02629 ]
 [-0.02672 ]
 [-0.0268  ]
 [-0.02649 ]
 [-0.02611 ]
 [-0.02554 ]
 [-0.02492 ]
 [-0.02423 ]
 [-0.02348 ]
 [-0.02281 ]
 [-0.02208 ]
 [-0.0214  ]
 [-0.02061 ]
 [-0.01984 ]
 [-0.01898 ]
 [-0.01811 ]
 [-0.01729 ]
 [-0.01656 ]
 [-0.01613 ]
 [-0.01588 ]
 [-0.01555 ]
 [-0.01538 ]
 [-0.01578 ]
 [-0.01572 ]
 [-0.01558 ]
 [-0.01526 ]
 [-0.01484 ]
 [-0.013596]
 [-0.01231 ]
 [-0.01112 ]
 [-0.01004 ]
 [-0.009026]
 [-0.00809 ]


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: nan - val_loss: 0.0237
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0230
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0231
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0246
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
[[0.03232]
 [0.03232]
 [0.03226]
 [0.0322 ]
 [0.03214]
 [0.03195]
 [0.03232]
 [0.0331 ]
 [0.03394]
 [0.03467]
 [0.03503]
 [0.0351 ]
 [0.03497]
 [0.0348 ]
 [0.03464]
 [0.03455]
 [0.0346 ]
 [0.03473]
 [0.03485]
 [0.0351 ]
 [0.03516]
 [0.03497]
 [0.03488]
 [0.0348 ]
 [0.03482]
 [0.03503]
 [0.03564]
 [0.03635]
 [0.03723]
 [0.03827]
 [0.0392 ]
 [0.0401 ]
 [0.04074]
 [0.04114]
 [0.04153]
 [0.04184]
 [0.04205]
 [0.04233]
 [0.0427 ]
 [0.0432 ]
 [0.04373]
 [0.04443]
 [0.04456]
 [0.0445 ]
 [0.04456]
 [0.04486]
 [0.04532]
 [0.04587]
 [0.0463 ]
 [0.04645]
 [0.04654]
 [0.04645]
 [0.04578]
 [0.04468]
 [0.0433 ]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0229
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0230
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: nan - val_loss: 0.0229
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0232
[[-0.004745]
 [-0.0047  ]
 [-0.004646]
 [-0.004593]
 [-0.004414]
 [-0.00421 ]
 [-0.004005]
 [-0.003899]
 [-0.003883]
 [-0.00397 ]
 [-0.00408 ]
 [-0.00423 ]
 [-0.004475]
 [-0.004765]
 [-0.005028]
 [-0.005253]
 [-0.005417]
 [-0.005665]
 [-0.005947]
 [-0.006207]
 [-0.006382]
 [-0.00664 ]
 [-0.006893]
 [-0.007236]
 [-0.007473]
 [-0.007717]
 [-0.00784 ]
 [-0.007786]
 [-0.007786]
 [-0.00693 ]
 [-0.006107]
 [-0.00551 ]
 [-0.004932]
 [-0.004467]
 [-0.003937]
 [-0.003391]
 [-0.00314 ]
 [-0.003033]
 [-0.002945]
 [-0.002884]
 [-0.002762]
 [-0.002598]
 [-0.002483]
 [-0.002304]
 [-0.002083]
 [-0.001903]
 [-0.0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - loss: nan - val_loss: 0.0344
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: nan - val_loss: 0.0347
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: nan - val_loss: 0.0347
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0343
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: nan - val_loss: 0.0343
[[-1.2417e-03]
 [-1.1311e-03]
 [-9.9754e-04]
 [-9.8991e-04]
 [-9.8419e-04]
 [-9.4795e-04]
 [-9.0981e-04]
 [-8.8692e-04]
 [-9.2506e-04]
 [-9.2506e-04]
 [-8.9455e-04]
 [-6.3515e-04]
 [-3.6621e-04]
 [-1.1826e-04]
 [ 9.3460e-05]
 [ 2.4605e-04]
 [ 4.5013e-04]
 [ 7.1812e-04]
 [ 1.0357e-03]
 [ 1.3313e-03]
 [ 1.5926e-03]
 [ 1.8425e-03]
 [ 2.1019e-03]
 [ 2.5921e-03]
 [ 3.1376e-03]
 [ 3.3951e-03]
 [ 3.2101e-03]
 [ 2.8648e-03]
 [ 3.1204e-03]
 [ 3.4370e-03]
 [ 3.7766e-03]
 [ 4.1008e-03]
 [ 4.5013e-03]
 [ 4.8294e-03]
 [ 5.0430e-03]
 [ 5.1804e-03]
 [ 5.2567e-03]
 [ 5.3940e-03]
 [ 5.3329e-03]
 [ 5.3062e-03]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0119
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0114
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0114
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0113
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0115
[[ 0.01181  ]
 [ 0.01173  ]
 [ 0.01187  ]
 [ 0.01168  ]
 [ 0.0111   ]
 [ 0.00996  ]
 [ 0.008026 ]
 [ 0.005646 ]
 [ 0.003626 ]
 [ 0.002096 ]
 [ 0.00076  ]
 [ 0.0001459]
 [-0.0002856]
 [-0.0005856]
 [-0.000785 ]
 [-0.000801 ]
 [-0.0003018]
 [ 0.000681 ]
 [ 0.001722 ]
 [ 0.00321  ]
 [ 0.00552  ]
 [ 0.00787  ]
 [ 0.00985  ]
 [ 0.010605 ]
 [ 0.01105  ]
 [ 0.01187  ]
 [ 0.01283  ]
 [ 0.01403  ]
 [ 0.01542  ]
 [ 0.01704  ]
 [ 0.01894  ]
 [ 0.0208   ]
 [ 0.02248  ]
 [ 0.02359  ]
 [ 0.02461  ]
 [ 0.02565  ]
 [ 0.02695  ]
 [ 0.02791  ]
 [ 0.02768  ]
 [ 0.02693  ]
 [ 0.02626  ]
 [ 0.02583  ]
 [ 0.02571  ]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - loss: nan - val_loss: 0.0460
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: nan - val_loss: 0.0458
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: nan - val_loss: 0.0460
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0457
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: nan - val_loss: 0.0461
[[ 1.0748e-03]
 [ 1.1988e-03]
 [ 1.2484e-03]
 [ 1.3227e-03]
 [ 1.2827e-03]
 [ 1.2369e-03]
 [ 1.1530e-03]
 [ 1.1415e-03]
 [ 1.2541e-03]
 [ 1.4467e-03]
 [ 1.7214e-03]
 [ 1.9913e-03]
 [ 2.3346e-03]
 [ 2.8381e-03]
 [ 3.4523e-03]
 [ 5.2299e-03]
 [ 7.3891e-03]
 [ 9.6588e-03]
 [ 1.1879e-02]
 [ 1.4084e-02]
 [ 1.6083e-02]
 [ 1.7654e-02]
 [ 1.9409e-02]
 [ 2.0340e-02]
 [ 2.1210e-02]
 [ 2.2095e-02]
 [ 2.2842e-02]
 [ 2.3666e-02]
 [ 2.4490e-02]
 [ 2.4811e-02]
 [ 2.5009e-02]
 [ 2.5330e-02]
 [ 2.5742e-02]
 [ 2.6291e-02]
 [ 2.6794e-02]
 [ 2.7298e-02]
 [ 2.7771e-02]
 [ 2.8046e-02]
 [ 2.8198e-02]
 [ 2.8259e-02]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0345
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0343
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0349
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0349
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0343
[[ 0.01714  ]
 [ 0.0169   ]
 [ 0.01634  ]
 [ 0.01563  ]
 [ 0.014786 ]
 [ 0.01395  ]
 [ 0.01309  ]
 [ 0.01207  ]
 [ 0.01108  ]
 [ 0.0101   ]
 [ 0.00902  ]
 [ 0.00781  ]
 [ 0.006626 ]
 [ 0.0056   ]
 [ 0.004284 ]
 [ 0.002724 ]
 [ 0.0011015]
 [-0.0005207]
 [-0.002079 ]
 [-0.003262 ]
 [-0.004414 ]
 [-0.005527 ]
 [-0.00687  ]
 [-0.00807  ]
 [-0.009186 ]
 [-0.00993  ]
 [-0.01085  ]
 [-0.01167  ]
 [-0.012314 ]
 [-0.012314 ]
 [-0.01251  ]
 [-0.01271  ]
 [-0.01286  ]
 [-0.01291  ]
 [-0.01309  ]
 [-0.01317  ]
 [-0.01326  ]
 [-0.01335  ]
 [-0.01338  ]
 [-0.01343  ]
 [-0.01312  ]
 [-0.01247  ]
 [-0.011734 ]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0582
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0582
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0575
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0577
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0574
[[0.05798]
 [0.05743]
 [0.05698]
 [0.0565 ]
 [0.0561 ]
 [0.0559 ]
 [0.0557 ]
 [0.05545]
 [0.05536]
 [0.0554 ]
 [0.05542]
 [0.05554]
 [0.0558 ]
 [0.0561 ]
 [0.0564 ]
 [0.05695]
 [0.05753]
 [0.05814]
 [0.05884]
 [0.05957]
 [0.05975]
 [0.06015]
 [0.06027]
 [0.06042]
 [0.06052]
 [0.06055]
 [0.06046]
 [0.06046]
 [0.0604 ]
 [0.06033]
 [0.06033]
 [0.06036]
 [0.06024]
 [0.06024]
 [0.06   ]
 [0.05966]
 [0.05948]
 [0.05917]
 [0.0588 ]
 [0.05835]
 [0.05795]
 [0.05746]
 [0.057  ]
 [0.0565 ]
 [0.056  ]
 [0.0555 ]
 [0.05533]
 [0.0554 ]
 [0.05545]
 [0.05557]
 [0.0556 ]
 [0.05554]
 [0.05566]
 [0.0559 ]
 [0.05612]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - loss: nan - val_loss: 0.0114
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: nan - val_loss: 0.0114
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0114
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0116
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0114
[[ 0.007057 ]
 [ 0.00683  ]
 [ 0.006668 ]
 [ 0.00643  ]
 [ 0.00602  ]
 [ 0.0055   ]
 [ 0.00459  ]
 [ 0.00364  ]
 [ 0.002502 ]
 [ 0.001394 ]
 [ 0.0004091]
 [-0.000307 ]
 [-0.0007153]
 [-0.001036 ]
 [-0.001322 ]
 [-0.001587 ]
 [-0.00186  ]
 [-0.002127 ]
 [-0.00234  ]
 [-0.002619 ]
 [-0.002802 ]
 [-0.003153 ]
 [-0.003149 ]
 [-0.00295  ]
 [-0.002798 ]
 [-0.002817 ]
 [-0.002821 ]
 [-0.00284  ]
 [-0.002794 ]
 [-0.002768 ]
 [-0.002642 ]
 [-0.002531 ]
 [-0.002653 ]
 [-0.002932 ]
 [-0.003477 ]
 [-0.004005 ]
 [-0.004623 ]
 [-0.005127 ]
 [-0.005234 ]
 [-0.0055   ]
 [-0.005745 ]
 [-0.00608  ]
 [-0.00638  ]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0458
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0457
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0458
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0459
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0459
[[0.00925 ]
 [0.00948 ]
 [0.00975 ]
 [0.00987 ]
 [0.00992 ]
 [0.00978 ]
 [0.00951 ]
 [0.00902 ]
 [0.00857 ]
 [0.008194]
 [0.007755]
 [0.007687]
 [0.007694]
 [0.007935]
 [0.008255]
 [0.0088  ]
 [0.009384]
 [0.010315]
 [0.011215]
 [0.01213 ]
 [0.013   ]
 [0.01373 ]
 [0.01427 ]
 [0.01468 ]
 [0.01495 ]
 [0.01488 ]
 [0.014694]
 [0.014496]
 [0.014404]
 [0.01431 ]
 [0.01416 ]
 [0.01396 ]
 [0.0139  ]
 [0.01396 ]
 [0.01395 ]
 [0.013855]
 [0.01375 ]
 [0.01352 ]
 [0.01309 ]
 [0.01242 ]
 [0.0117  ]
 [0.0107  ]
 [0.009636]
 [0.008766]
 [0.00811 ]
 [0.00799 ]
 [0.007996]
 [0.00797 ]
 [0.00796 ]
 [0.0081  ]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0806
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0803
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 0.0806
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: nan - val_loss: 0.0811
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0824
[[-0.01497 ]
 [-0.015335]
 [-0.01576 ]
 [-0.01593 ]
 [-0.016   ]
 [-0.01613 ]
 [-0.01643 ]
 [-0.01668 ]
 [-0.01671 ]
 [-0.01663 ]
 [-0.01657 ]
 [-0.01682 ]
 [-0.01709 ]
 [-0.01724 ]
 [-0.0172  ]
 [-0.01704 ]
 [-0.01668 ]
 [-0.01624 ]
 [-0.01593 ]
 [-0.01566 ]
 [-0.01547 ]
 [-0.01553 ]
 [-0.01599 ]
 [-0.01665 ]
 [-0.01723 ]
 [-0.01743 ]
 [-0.01743 ]
 [-0.01729 ]
 [-0.0169  ]
 [-0.0164  ]
 [-0.01587 ]
 [-0.015396]
 [-0.01503 ]
 [-0.01489 ]
 [-0.01482 ]
 [-0.014694]
 [-0.01466 ]
 [-0.01466 ]
 [-0.01454 ]
 [-0.01445 ]
 [-0.01434 ]
 [-0.01401 ]
 [-0.01369 ]
 [-0.013245]
 [-0.01274 ]
 [-0.01161 ]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0227
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0230
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0228
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0230
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0230
[[-0.05118 ]
 [-0.05115 ]
 [-0.05054 ]
 [-0.04953 ]
 [-0.0483  ]
 [-0.0472  ]
 [-0.04602 ]
 [-0.04446 ]
 [-0.04266 ]
 [-0.0404  ]
 [-0.03824 ]
 [-0.03687 ]
 [-0.0356  ]
 [-0.03436 ]
 [-0.033   ]
 [-0.03152 ]
 [-0.03014 ]
 [-0.02919 ]
 [-0.02864 ]
 [-0.02881 ]
 [-0.02913 ]
 [-0.02965 ]
 [-0.03017 ]
 [-0.03032 ]
 [-0.03062 ]
 [-0.03072 ]
 [-0.03105 ]
 [-0.0314  ]
 [-0.03165 ]
 [-0.03165 ]
 [-0.03186 ]
 [-0.0322  ]
 [-0.03278 ]
 [-0.03314 ]
 [-0.03342 ]
 [-0.03363 ]
 [-0.03397 ]
 [-0.0345  ]
 [-0.0347  ]
 [-0.0346  ]
 [-0.03415 ]
 [-0.03326 ]
 [-0.03244 ]
 [-0.03244 ]
 [-0.0326  ]
 [-0.03195 ]
 [-0.03

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: nan - val_loss: 0.0341
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0347
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0344
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0349
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0356
[[-0.003557 ]
 [-0.003805 ]
 [-0.00421  ]
 [-0.00478  ]
 [-0.005512 ]
 [-0.00666  ]
 [-0.00807  ]
 [-0.00962  ]
 [-0.01135  ]
 [-0.01317  ]
 [-0.01481  ]
 [-0.01677  ]
 [-0.01862  ]
 [-0.02026  ]
 [-0.02208  ]
 [-0.02373  ]
 [-0.0254   ]
 [-0.0264   ]
 [-0.02808  ]
 [-0.02962  ]
 [-0.0309   ]
 [-0.0319   ]
 [-0.03232  ]
 [-0.03204  ]
 [-0.03156  ]
 [-0.03075  ]
 [-0.02956  ]
 [-0.02821  ]
 [-0.02687  ]
 [-0.02559  ]
 [-0.02383  ]
 [-0.02173  ]
 [-0.01973  ]
 [-0.0178   ]
 [-0.01588  ]
 [-0.01378  ]
 [-0.0119   ]
 [-0.01016  ]
 [-0.00853  ]
 [-0.007004 ]
 [-0.00532  ]
 [-0.00313  ]
 [-0.000605 ]
 [ 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - loss: nan - val_loss: 0.0113
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0115
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 0.0115
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0113
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0115
[[-0.005566]
 [-0.005703]
 [-0.005924]
 [-0.005997]
 [-0.005985]
 [-0.005688]
 [-0.00531 ]
 [-0.004898]
 [-0.00463 ]
 [-0.004425]
 [-0.004482]
 [-0.004803]
 [-0.005352]
 [-0.00601 ]
 [-0.0069  ]
 [-0.00784 ]
 [-0.00865 ]
 [-0.00929 ]
 [-0.00986 ]
 [-0.01047 ]
 [-0.01106 ]
 [-0.01166 ]
 [-0.012115]
 [-0.01251 ]
 [-0.01286 ]
 [-0.01315 ]
 [-0.013245]
 [-0.013245]
 [-0.012924]
 [-0.012344]
 [-0.01164 ]
 [-0.010956]
 [-0.01021 ]
 [-0.00955 ]
 [-0.00871 ]
 [-0.007763]
 [-0.007023]
 [-0.00652 ]
 [-0.00623 ]
 [-0.006035]
 [-0.006023]
 [-0.006077]
 [-0.005997]
 [-0.005886]
 [-0.005753]
 [-0.00547 ]
 [-0.0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: nan - val_loss: 0.0233
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0247
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0230
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: nan - val_loss: 0.0231
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0229
[[0.0239 ]
 [0.02394]
 [0.02406]
 [0.02417]
 [0.02425]
 [0.0243 ]
 [0.02434]
 [0.02432]
 [0.02428]
 [0.02423]
 [0.02425]
 [0.02428]
 [0.02432]
 [0.02446]
 [0.02475]
 [0.02505]
 [0.02542]
 [0.02565]
 [0.02579]
 [0.0259 ]
 [0.02591]
 [0.0258 ]
 [0.02574]
 [0.02571]
 [0.02559]
 [0.02559]
 [0.02571]
 [0.02588]
 [0.02605]
 [0.0263 ]
 [0.02643]
 [0.02643]
 [0.0263 ]
 [0.026  ]
 [0.02568]
 [0.0255 ]
 [0.02533]
 [0.02518]
 [0.02502]
 [0.02493]
 [0.02484]
 [0.02492]
 [0.02515]
 [0.0254 ]
 [0.02565]
 [0.02617]
 [0.02693]
 [0.02756]
 [0.02824]
 [0.02873]
 [0.02908]
 [0.0293 ]
 [0.02934]
 [0.02905]
 [0.02855]

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: nan - val_loss: 0.0114
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0115
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0119
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0116
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: nan - val_loss: 0.0114
[[-3.3684e-03]
 [-3.2768e-03]
 [-3.1929e-03]
 [-3.1471e-03]
 [-3.0365e-03]
 [-2.9449e-03]
 [-2.7618e-03]
 [-2.5749e-03]
 [-2.3613e-03]
 [-2.2812e-03]
 [-2.2583e-03]
 [-2.3270e-03]
 [-2.4223e-03]
 [-2.5711e-03]
 [-2.6627e-03]
 [-2.7313e-03]
 [-2.7351e-03]
 [-2.7275e-03]
 [-2.7542e-03]
 [-2.7657e-03]
 [-2.7313e-03]
 [-2.5749e-03]
 [-2.4147e-03]
 [-2.2125e-03]
 [-2.1133e-03]
 [-2.1095e-03]
 [-2.2469e-03]
 [-2.3460e-03]
 [-2.6283e-03]
 [-2.8305e-03]
 [-2.9259e-03]
 [-2.9068e-03]
 [-2.7390e-03]
 [-2.5558e-03]
 [-2.2888e-03]
 [-1.9035e-03]
 [-1.4648e-03]
 [-1.0109e-03]
 [-4.7302e-04]
 [-6.4850e-05]
 

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: nan - val_loss: 0.0374
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0354
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0369
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0346
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
[[-0.06696]
 [-0.06744]
 [-0.06805]
 [-0.06885]
 [-0.0699 ]
 [-0.07104]
 [-0.072  ]
 [-0.07294]
 [-0.0738 ]
 [-0.0746 ]
 [-0.07526]
 [-0.0768 ]
 [-0.07825]
 [-0.07965]
 [-0.0805 ]
 [-0.0814 ]
 [-0.0821 ]
 [-0.08246]
 [-0.08234]
 [-0.0817 ]
 [-0.08093]
 [-0.0808 ]
 [-0.0803 ]
 [-0.0796 ]
 [-0.07886]
 [-0.07764]
 [-0.0758 ]
 [-0.0739 ]
 [-0.07166]
 [-0.0695 ]
 [-0.06757]
 [-0.0658 ]
 [-0.06445]
 [-0.0633 ]
 [-0.06213]
 [-0.06067]
 [-0.05978]
 [-0.05902]
 [-0.05823]
 [-0.05734]
 [-0.0566 ]
 [-0.0556 ]
 [-0.05542]
 [-0.05548]
 [-0.05545]
 [-0.05466]
 [-0.05304]
 [-0.05078]
 [-0.0486 ]
 [-0.04672]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0574
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0579
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0592
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0578
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0605
[[0.002106]
 [0.002514]
 [0.002853]
 [0.00336 ]
 [0.003433]
 [0.002907]
 [0.00232 ]
 [0.001856]
 [0.001474]
 [0.001413]
 [0.001453]
 [0.001854]
 [0.002193]
 [0.002686]
 [0.003052]
 [0.003456]
 [0.003784]
 [0.003925]
 [0.00441 ]
 [0.00492 ]
 [0.005127]
 [0.005116]
 [0.00505 ]
 [0.004986]
 [0.00487 ]
 [0.00481 ]
 [0.00483 ]
 [0.004898]
 [0.00499 ]
 [0.0049  ]
 [0.00482 ]
 [0.004635]
 [0.00418 ]
 [0.00396 ]
 [0.003803]
 [0.003555]
 [0.003483]
 [0.00343 ]
 [0.003567]
 [0.00375 ]
 [0.004093]
 [0.004494]
 [0.004818]
 [0.00535 ]
 [0.0059  ]
 [0.006363]
 [0.00641 ]
 [0.00637 ]
 [0.006332]
 [0.006256]
 [0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - loss: nan - val_loss: 0.0115
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: nan - val_loss: 0.0114
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0117
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0114
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0114
[[-0.0226 ]
 [-0.0223 ]
 [-0.0221 ]
 [-0.02197]
 [-0.022  ]
 [-0.02213]
 [-0.02232]
 [-0.02257]
 [-0.0229 ]
 [-0.02327]
 [-0.02362]
 [-0.024  ]
 [-0.02435]
 [-0.02457]
 [-0.02463]
 [-0.02472]
 [-0.02473]
 [-0.02483]
 [-0.02496]
 [-0.02518]
 [-0.02542]
 [-0.0257 ]
 [-0.02603]
 [-0.02629]
 [-0.02649]
 [-0.02652]
 [-0.02641]
 [-0.0262 ]
 [-0.02586]
 [-0.02576]
 [-0.02582]
 [-0.02597]
 [-0.02621]
 [-0.0265 ]
 [-0.02693]
 [-0.02748]
 [-0.02817]
 [-0.02882]
 [-0.02937]
 [-0.02977]
 [-0.02992]
 [-0.02979]
 [-0.02945]
 [-0.02895]
 [-0.02823]
 [-0.02744]
 [-0.0268 ]
 [-0.02641]
 [-0.02617]
 [-0.0261 ]
 [-0

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0352
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0346
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: nan - val_loss: 0.0345
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0344
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0346
[[-0.0321 ]
 [-0.03308]
 [-0.03384]
 [-0.03452]
 [-0.03506]
 [-0.03537]
 [-0.03543]
 [-0.03525]
 [-0.03473]
 [-0.03394]
 [-0.0329 ]
 [-0.03174]
 [-0.03041]
 [-0.02908]
 [-0.02798]
 [-0.02711]
 [-0.02644]
 [-0.02583]
 [-0.02525]
 [-0.02487]
 [-0.02469]
 [-0.02464]
 [-0.02475]
 [-0.0251 ]
 [-0.02544]
 [-0.02591]
 [-0.0265 ]
 [-0.02707]
 [-0.02754]
 [-0.02791]
 [-0.02907]
 [-0.03062]
 [-0.03217]
 [-0.0336 ]
 [-0.03574]
 [-0.03796]
 [-0.04044]
 [-0.04282]
 [-0.0447 ]
 [-0.0467 ]
 [-0.0488 ]
 [-0.0509 ]
 [-0.05255]
 [-0.0541 ]
 [-0.0556 ]
 [-0.05713]
 [-0.05786]
 [-0.05814]
 [-0.05807]
 [-0.05707]
 [

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: nan - val_loss: 0.0126
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: nan - val_loss: 0.0115
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: nan - val_loss: 0.0113
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: nan - val_loss: 0.0113
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: nan - val_loss: 0.0115
[[0.02156]
 [0.02127]
 [0.02107]
 [0.02141]
 [0.02184]
 [0.02284]
 [0.02379]
 [0.02502]
 [0.02644]
 [0.02771]
 [0.02911]
 [0.02986]
 [0.0305 ]
 [0.03044]
 [0.03009]
 [0.02974]
 [0.02942]
 [0.02919]
 [0.02905]
 [0.02832]
 [0.02763]
 [0.02678]
 [0.02615]
 [0.02531]
 [0.02414]
 [0.02321]
 [0.02216]
 [0.02142]
 [0.02107]
 [0.02081]
 [0.02054]
 [0.02046]
 [0.02045]
 [0.02043]
 [0.02036]
 [0.02022]
 [0.01999]
 [0.01984]
 [0.01976]
 [0.0196 ]
 [0.01945]
 [0.01947]
 [0.01978]
 [0.01993]
 [0.02026]
 [0.02065]
 [0.02106]
 [0.0216 ]
 [0.02182]
 [0.02182]
 [0.02237]
 [0.02301]
 [0.0236 ]
 [0.02414]
 [0.025